route:
    receiver: 'email'
    repeat_interval: 1s

receivers:
    - name: 'email'
      email_configs:
      - to: 'tuannghiemtien97@gmail.com'
        from: 'nghiemthihachi@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_password: 'khongcomatkhau'
        auth_username: 'nghiemthihachi@gmail.com'
        auth_identity: 'nghiemthihachi@gmail.com'
        send_resolved: true
        headers:
          subject: tuanlinhchi (nghiemtuan.name.vn) alert
        html: >-
          <p style="color: blue">[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          </p><hr />

          {{ range .Alerts -}}
          <h1>Alert: [{{ .Annotations.instance }}][{{ if .Labels.severity }}{{ .Labels.severity }}{{ end }}] {{ .Annotations.summary }}</h1>
          <p><strong>* Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>* Details:</strong></p>
            <ul>
            {{ range .Labels.SortedPairs }}<li>{{ .Name }}: {{ .Value }}</li>
            {{ end }}
            </ul>
          <hr />
          {{ end }}
