route:
    receiver: 'email'
    repeat_interval: 30s

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#<channel-name>'
            api_url: 'https://hooks.slack.com/services/<webhook-id>'

    - name: 'email'
      email_configs:
        - to: 'tuannghiemtien97@gmail.com'
          from: 'nghiemthihachi@gmail.com'
          smarthost: smtp.gmail.com:587
          auth_password: 'khongcomatkhau'
          send_resolved: true